{"refs": [], "id": "", "subject": "[Radiance-general] Genskyvec.pl error on Windows (was: Re: Pythonscript)", "email": "Robert.Guglielmetti at nrel.gov", "body": "Message-ID: <CC2C6C15.127AF%robert.guglielmetti@nrel.gov>\n\nLooked at this a bit this morning, and actually I can't get the correct behavior from Genskyvec on Windows even using the program directly. A really simple example:\n\nC:\\gensky 6 21 12 <return>\n# gensky 6 21 12\n# Local solar time: 11.84\n# Solar altitude and azimuth: 75.5 -8.8\n# Ground ambient level: 18.2\n\nvoid light solar\n0\n0\n3 7.18e+006 7.18e+006 7.18e+006\n\nsolar source sun\n0\n0\n4 0.038263 -0.247650 0.968094 0.5\n\nvoid brightfunc skyfunc\n2 skybr skybright.cal\n0\n7 1 3.16e+001 3.02e+001 1.65e+000 0.038263 -0.247650 0.968094\n\nC:\\gensky 6 21 12 | genskyvec.pl -m 1\nBad sky description!\n\nGensky prints a valid description to STDOUT, but when I pipe it to genskyvec, it fails the error check loop in lines 25-45. I'm using v 2.8 of genskyvec.pl, from 2012.06.28. Ideas?\n\n- Rob\n\n\n", "isquestion": false, "replyTo": "<CAKGV-k1cBnaNuy9PC8fUKqq72KC-=G6Q3v9NdJU8R3xB6CZ=FQ@mail.gmail.com>", "tags": [], "sender": "Guglielmetti, Robert", "datetime": "Wed, 18 Jul 2012 13:43:27 -0600"}