{"topic": "problem of gencumulativesky driven through Python", "category": "radiance-general", "attachments": [], "created_by_name": "Joe Smith", "created_at": "February 18, 2015 at 07:32PM", "body": "Hi, guys,\n\n\nI don't know if you can kindly advise me on a Python related problem, or\nsuggest a source for help:\n\n\n1. the following gencumulativesky command runs OK in the terminal of Mac OS\nusing London's weather file:\n*GenCumulativeSky  +s1  -a 51.15  -o 0.18  -m -0.0 -h 0  -E  -time 0 24\n-date 1 1 12 31 ./London.epw > ./gcs_London.cal*\n\n\n... with two lines of error message:\n\n\n\n\n*There were 4586 sun up hours in this climate fileTotal Ibh/Lbh: 0.000000*\n\n\n2. But I can't get it working at all by running a Python script with the\nfollowing contents:\n\n\n\n\n*import oscmd = \"GenCumulativeSky  +s1  -a 51.15  -o 0.18  -m -0.0    -h 0\n-E  -time 0 24  -date 1 1 12 31 ./London.epw >\n./gcs_London.cal\"os.system(cmd)*\n\n\nThere is no error message in the Python IDLE, but the .cal file generated\nis zero ...\n\n\n\n\nMoreover, I got a lot more error messages when running the gencumulativesky\nprogram directly in the terminal of Mac OS X using Singapore's weather file:\n\n\nCommand:\n*GenCumulativeSky  +s1  -a 1.37  -o -103.98  -m -120.0    -h 0  -E  -time 0\n24  -date 1 1 12 31 ./SGP_Singapore.486980_IWEC.epw > ./gcs_SG.cal*\n\n\nErrors:\n\n\n\n\n\n\n\n\n*Error!  Solar altitude < 6 degrees and Idh > 10 W/m^2 on day 1!\nAttempting to continue!......Error!  Solar altitude < 6 degrees and Idh >\n10 W/m^2 on day 365!  Attempting to continue!There were 4354 sun up hours\nin this climate fileTotal Ibh/Lbh: 0.000000*\n\n\n\n\nThanks for your help!\n___\n<sup>Automatically generated content from [radiance mailing-list](https://radiance-online.org/pipermail/radiance-general/2015-February/010747.html).</sup>", "id": "radiance-general_010747", "created_by": "Joe_Smith"}